In [4]:
import pandas as pd
from scipy.io import arff
import matplotlib.pyplot as plt

## Read in data
arff_file = arff.loadarff('../data/AbnormalHeartbeat_TRAIN.arff')
df = pd.DataFrame(arff_file[0])
df['target'] = df['target'].apply(lambda x: 'Abnormal' if str(x) == "b'Abnormal'" else 'Normal')

dft = df.T
dft.columns = ['Patient'+f'{i}' for i in range(len(dft.columns))]
dft

,Patient0,Patient1,Patient2,Patient3,Patient4,Patient5,Patient6,Patient7,Patient8,Patient9,...,Patient194,Patient195,Patient196,Patient197,Patient198,Patient199,Patient200,Patient201,Patient202,Patient203
att1,-0.020874,-0.004303,-0.006073,0.007202,-0.024231,0.058075,0.266479,-0.01001,0.016571,-0.006348,...,0.000427,0.031067,-0.000916,0.045136,-0.000885,-0.032227,0.00238,-0.008881,0.024139,0.001709
att2,-0.045197,-0.009003,-0.012054,0.015594,-0.051056,0.12204,0.572998,-0.02063,0.035553,-0.012451,...,0.00061,0.064636,-0.003265,0.072937,-0.002197,-0.056732,0.005127,-0.019379,0.049408,0.005188
att3,-0.043945,-0.008728,-0.009979,0.013245,-0.045929,0.108307,0.52536,-0.016144,0.033813,-0.010162,...,0.001282,0.054565,-0.006042,0.038116,-0.002045,-0.034149,0.005737,-0.01825,0.035004,0.006805
att4,-0.049011,-0.009918,-0.010742,0.015594,-0.049835,0.113769,0.572662,-0.017151,0.038177,-0.009338,...,0.00116,0.056396,-0.007233,0.023285,-0.001038,-0.024109,0.007263,-0.020325,0.030121,0.009277
att5,-0.0466,-0.009949,-0.009888,0.015015,-0.048828,0.105316,0.552521,-0.014587,0.039337,-0.007538,...,0.000305,0.0513,-0.009369,-0.000977,-0.001343,-0.005127,0.008575,-0.019989,0.021027,0.014404
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
att18527,-0.032532,0.015961,0.032959,0.030304,-0.310944,-0.009674,-0.021118,-0.010345,-0.034119,0.004333,...,-0.005493,0.022247,0.015259,-0.114441,-0.002441,-0.017151,-0.001984,0.086121,-0.009369,0.008148
att18528,-0.032501,0.016205,0.039673,0.030426,-0.304504,-0.013153,-0.019226,-0.008209,-0.035278,0.005768,...,-0.007233,0.018738,0.01593,-0.081146,-0.00238,-0.014282,-0.003998,0.073975,0.000275,0.008453
att18529,-0.031982,0.016357,0.044739,0.030212,-0.298065,-0.01413,-0.015381,-0.006958,-0.037476,0.006683,...,-0.009644,0.017548,0.016266,-0.053589,-0.003174,-0.008087,-0.005981,0.059906,0.009033,0.008423
att18530,-0.033783,0.017792,0.050018,0.031219,-0.282532,-0.01825,-0.014862,-0.005981,-0.03772,0.007843,...,-0.011658,0.019592,0.016632,-0.026337,-0.001648,-0.007111,-0.00766,0.043701,0.018524,0.008087
target,Abnormal,Abnormal,Abnormal,Abnormal,Abnormal,Abnormal,Abnormal,Abnormal,Abnormal,Abnormal,...,Normal,Normal,Normal,Normal,Normal,Normal,Normal,Normal,Normal,Normal

In [30]:
len(df.select_dtypes(include=['number']).columns)

18530

In [34]:
df

,att1,att2,att3,att4,att5,att6,att7,att8,att9,att10,...,att18522,att18523,att18524,att18525,att18526,att18527,att18528,att18529,att18530,target
0,-0.020874,-0.045197,-0.043945,-0.049011,-0.046600,-0.048004,-0.045563,-0.041962,-0.037170,-0.029541,...,-0.044037,-0.041382,-0.040192,-0.036194,-0.034424,-0.032532,-0.032501,-0.031982,-0.033783,Abnormal
1,-0.004303,-0.009003,-0.008728,-0.009918,-0.009949,-0.010681,-0.010773,-0.011200,-0.011230,-0.011169,...,0.016815,0.016846,0.016754,0.015839,0.015930,0.015961,0.016205,0.016357,0.017792,Abnormal
2,-0.006073,-0.012054,-0.009979,-0.010742,-0.009888,-0.010406,-0.010101,-0.009979,-0.010162,-0.010315,...,-0.006775,0.001740,0.010071,0.017914,0.025574,0.032959,0.039673,0.044739,0.050018,Abnormal
3,0.007202,0.015594,0.013245,0.015594,0.015015,0.017792,0.018250,0.020660,0.021240,0.022797,...,0.040466,0.037994,0.036011,0.033295,0.032074,0.030304,0.030426,0.030212,0.031219,Abnormal
4,-0.024231,-0.051056,-0.045929,-0.049835,-0.048828,-0.049316,-0.048401,-0.047913,-0.046051,-0.045837,...,-0.277618,-0.294800,-0.303314,-0.309082,-0.314179,-0.310944,-0.304504,-0.298065,-0.282532,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,-0.032227,-0.056732,-0.034149,-0.024109,-0.005127,0.007629,0.023743,0.037292,0.051758,0.064087,...,-0.020721,-0.020233,-0.019501,-0.018433,-0.018005,-0.017151,-0.014282,-0.008087,-0.007111,Normal
200,0.002380,0.005127,0.005737,0.007263,0.008575,0.010742,0.012970,0.017212,0.022003,0.027954,...,0.005707,0.006683,0.006012,0.003601,0.000427,-0.001984,-0.003998,-0.005981,-0.007660,Normal
201,-0.008881,-0.019379,-0.018250,-0.020325,-0.019989,-0.021271,-0.020905,-0.021423,-0.022522,-0.023438,...,0.115173,0.112854,0.108795,0.103119,0.095245,0.086121,0.073975,0.059906,0.043701,Normal
202,0.024139,0.049408,0.035004,0.030121,0.021027,0.012146,0.010773,0.009216,0.009735,0.006683,...,-0.049042,-0.042694,-0.037415,-0.028961,-0.019653,-0.009369,0.000275,0.009033,0.018524,Normal
203,0.001709,0.005188,0.006805,0.009277,0.014404,0.020020,0.024689,0.028015,0.029877,0.030426,...,0.005219,0.005127,0.005920,0.006989,0.007843,0.008148,0.008453,0.008423,0.008087,Normal

In [48]:
df['Patient'] = range(df.shape[0])
df = df.melt(id_vars = ['Patient'], value_vars = df.select_dtypes(include=['number']))

In [50]:
df.sort_values(by=['Patient', 'variable'])

         Patient  variable     value
0              0      att1 -0.020874
1836           0     att10 -0.029541
20196          0    att100 -0.001862
203796         0   att1000 -0.013824
2039796        0  att10000  0.030548
...          ...       ...       ...
2038979      203   att9995  0.013824
2039183      203   att9996  0.015137
2039387      203   att9997  0.015747
2039591      203   att9998  0.014984
2039795      203   att9999  0.013550

[3780120 rows x 3 columns]